### ISSUE TITLE
Todo: 

### ISSUE THREAD

**Issue by Yulife** [s0cks/Herbarium#2]
- [x] Fix book scaling so it works in all sizes

- [x] Make entries render with the overlay

- [ ] Text goes under overlay, kind of like a description

- [x] Fix font scaling

- [ ] Fix attack speed
